name: CI/CD

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install build

      - name: Install package in development mode
        run: pip install -e .

      - name: Build package
        run: python -m build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/*

  deploy:
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pip install build

      - name: Update project version
        run: |
          sed -i 's/version = ".*"/version = "${{ steps.version.outputs.VERSION }}"/' pyproject.toml
          sed -i 's/"version": ".*"/"version": "${{ steps.version.outputs.VERSION }}"/' server.json

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}

      # - name: Install mcp-publisher
      #   run: # TODO: Install mcp-publisher
      # - name: Login to MCP Registry
      #   run: mcp-publisher login github-oidc
      # - name: Publish to MCP Registry
      #   run: mcp-publisher publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}